collections:
  tags:
    output: true

permalink: /:categories/:title:output_ext

theme: jekyll-theme-minimal

title: Dion Ricky
description: >-
  Hello, I'm a computer science student and I want
  to share some of my learning experiences through writing
  on this blog. - Dion Ricky Saputra

plugins:
  - jemoji
